// src/common/enums/permissions.enum.ts
export enum Permission {
  // Organizations
  ORG_VIEW = 'ORG_VIEW',
  ORG_UPDATE = 'ORG_UPDATE',

  // Users & Roles
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // Properties & Units
  PROPERTY_VIEW = 'PROPERTY_VIEW',
  PROPERTY_CREATE = 'PROPERTY_CREATE',
  PROPERTY_UPDATE = 'PROPERTY_UPDATE',
  PROPERTY_DELETE = 'PROPERTY_DELETE',
  UNIT_VIEW = 'UNIT_VIEW',
  UNIT_CREATE = 'UNIT_CREATE',
  UNIT_UPDATE = 'UNIT_UPDATE',
  UNIT_DELETE = 'UNIT_DELETE',

  // Tenants & Leases
  TENANT_VIEW = 'TENANT_VIEW',
  TENANT_CREATE = 'TENANT_CREATE',
  TENANT_UPDATE = 'TENANT_UPDATE',
  TENANT_DELETE = 'TENANT_DELETE',
  LEASE_VIEW = 'LEASE_VIEW',
  LEASE_CREATE = 'LEASE_CREATE',
  LEASE_UPDATE = 'LEASE_UPDATE',
  LEASE_ACTIVATE = 'LEASE_ACTIVATE',
  LEASE_TERMINATE = 'LEASE_TERMINATE',

  // Financial & Payments
  INVOICE_VIEW = 'INVOICE_VIEW',
  INVOICE_EXPORT = 'INVOICE_EXPORT',
  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_CREATE = 'PAYMENT_CREATE',
  PAYMENT_RECONCILE = 'PAYMENT_RECONCILE',
  // Maintenance (BRD Section 44.6.1)
  MAINTENANCE_VIEW = 'MAINTENANCE_VIEW',
  MAINTENANCE_CREATE = 'MAINTENANCE_CREATE',
  MAINTENANCE_UPDATE = 'MAINTENANCE_UPDATE',
}